image:
  - Visual Studio 2017

before_build:
  - ps: >-
      $env:FSAC_TESTSUITE_MSBUILD_TOOLSVERSION_4_INSTALLED = if ("$env:APPVEYOR_BUILD_WORKER_IMAGE" -eq "Visual Studio 2017") { "0" } else { "1" };

build_script:
  - cmd: build.cmd All

test: off

artifacts:
  - path: bin\pkgs\*.zip
    name: pkgs

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
