name: $(Rev:r)
jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo "##vso[task.setvariable variable=PATH]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp;%PATH%"
    displayName: set fsi in PATH
  - script: build.cmd All
    displayName: build All
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'bin/pkgs'
      artifactName: 'pkgs'
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo "##vso[task.setvariable variable=FrameworkPathOverride]$(dirname $(which mono))/../lib/mono/4.5/"
    displayName: Workaround .NET reference assemblies on linux
  - script: ./build.sh All
    displayName: build All
- job: MacOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: echo "##vso[task.setvariable variable=FrameworkPathOverride]$(dirname $(which mono))/../lib/mono/4.5/"
    displayName: Workaround .NET reference assemblies on linux
  - script: ./build.sh All
    displayName: build All
